<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<form method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>"/>
    <input type="submit" value="Search"/>
</form>

<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><a href="<?= $routes[$user['id']] ?>"><?= htmlspecialchars($user['nickname']) ?></a></td>
        </tr>
    <?php endforeach; ?>
</table>