<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<h1>Hello, <?= htmlspecialchars($user['nickname']) ?>!</h1>
<a href="<?= $url['edit'] ?>">Edit user</a>
<p>
<form action="<?= $url['delete'] ?>" method="post">
    <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Remove">
</form>
</p>
